CREATE TABLE "user" (
  "id" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "counter" int
);

CREATE TABLE "mats" (
  "id" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "word" varchar,
  "count" int
);

CREATE TABLE "bad_words" (
	"id" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"word" varchar
);

CREATE TABLE "white_words" (
	"id" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"word" varchar
);

ALTER TABLE "mats" ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id");
ALTER TABLE "mats" ADD CONSTRAINT unique_email_per_username UNIQUE (user_id, word);
ALTER TABLE "user" ALTER COLUMN id DROP IDENTITY ;
