CREATE TABLE "user" (
  "id" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "counter" int
);

CREATE TABLE "mats" (
  "id" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "word" varchar,
  "count" int
);

ALTER TABLE "mats" ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id");
