name: Run script on commit

on:
  push:
    branches:
      - async

jobs:
  run-script:
    runs-on: self-hosted
    env:
      gachi_bot_token: ${{ secrets.TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run script
        run: ./run.sh
